In [19]:
import pandas as pd

df = pd.read_csv('data/encykorea.csv')

df.columns

Index(['page', 'card_index', 'category', 'title', 'href', 'summary',
       'contents'],
      dtype='object')

In [20]:
# 불필요한 컬럼 제거
df = df.drop(columns=['page','card_index','href'])

In [21]:
# # ['title', 'summary', 'content'] 각 컬럼 내 텍스트 큰따옴표로 감싸기

# df_wrapped = df.copy()
# df_wrapped["title"] = df_wrapped["title"].astype(str).apply(lambda x: f'"{x.replace("\"", "\"\"")}"')
# df_wrapped["summary"] = df_wrapped["summary"].astype(str).apply(lambda x: f'"{x.replace("\"", "\"\"")}"')
# df_wrapped["content"] = df_wrapped["content"].astype(str).apply(lambda x: f'"{x.replace("\"", "\"\"")}"')

In [22]:
# 결측치 처리 및 문자열 변환
text_cols = ["title", "summary", "contents"]

# 기본 전처리 (NaN → 빈 문자열, 공백 정리)
for c in text_cols:
    df[c] = df[c].fillna("").astype(str).str.replace("\n", " ").str.replace("\r", " ")
    df[c] = df[c].str.replace(r"\s+", " ", regex=True).str.strip()

In [23]:
# 따옴표 정규화
def normalize_quotes(x):
    return x.replace("“", '"').replace("”", '"').replace("‘", "'").replace("’", "'")
for c in text_cols:
    df[c] = df[c].apply(normalize_quotes)

In [ ]:
# import re

# # content_clean 생성 (한자 제거)
# HANJA_REGEX = r"[\u4E00-\u9FFF\u3400-\u4DBF\uF900-\uFAFF]"
# EMPTY_PAREN_REGEX = r"\(\s*\)"

# def remove_hanja_safely(text):
#     if not isinstance(text, str):
#         return ""
#     # 1) 한자 제거
#     t = re.sub(HANJA_REGEX, "", text)
#     # 2) 괄호 안이 완전히 공백이 된 경우 → 괄호 자체 제거
#     t = re.sub(EMPTY_PAREN_REGEX, "", t)
#     # 3) 양쪽 공백 정리
#     return t.strip()

# df["title_clean"] = df["title"].apply(remove_hanja_safely)
# df["summary_clean"] = df["summary"].apply(remove_hanja_safely)
# df["content_clean"] = df["contents"].apply(remove_hanja_safely)

In [24]:
df.head(4)

,category,title,summary,contents
0,물품,가(枷),죄수의 목에 채우는 형구(刑具).,보통 '칼'이라고 하였다. 칼은 마른 나무널판으로 만든 형틀로 죄수의 목에 씌워 보...
1,문헌,20공신회맹축 - 보사공신녹훈후(二十功臣會盟軸 - 保社功臣錄勳後),1694년 갑술환국으로 재집권한 서인이 보사공신 회맹 때의 회맹문과 복훈 때의 축문...,숙종대에 갑술환국(甲戌換局)으로 서인(西人)이 재집권하면서 보사공신(保社功臣) 중 ...
2,문헌,20공신회맹축 - 영국공신녹훈후(二十功臣會盟軸 - 寧國功臣錄勳後),"1646년 9월, 조선 제16대 왕 인조가 영국공신(寧國功臣)을 녹훈한 이후에 20...",이십공신회맹축(二十功臣會盟軸)은 1646년(인조 24)에 영국공신(寧國功臣)을 녹훈...
3,제도,가감역관(假監役官),조선 후기 선공감의 종9품 임시관직.,"1718년(숙종 44)에 처음으로 설치하였고, 정원은 3인이다. 이들은 감역관과 함..."

In [28]:
import csv

df.to_csv('data/encykorea_cleaned.csv', index=False, quoting=csv.QUOTE_ALL)

### 기존 뜻 요약 및 데이터에서 단어 추출 후 뜻 작성

In [1]:
import pandas as pd
import re

df = pd.read_csv("data/encykorea_cleaned.csv")
df.head(2)

,category,title,summary,contents
0,물품,가(枷),죄수의 목에 채우는 형구(刑具).,보통 '칼'이라고 하였다. 칼은 마른 나무널판으로 만든 형틀로 죄수의 목에 씌워 보...
1,문헌,20공신회맹축 - 보사공신녹훈후(二十功臣會盟軸 - 保社功臣錄勳後),1694년 갑술환국으로 재집권한 서인이 보사공신 회맹 때의 회맹문과 복훈 때의 축문...,숙종대에 갑술환국(甲戌換局)으로 서인(西人)이 재집권하면서 보사공신(保社功臣) 중 ...

In [2]:

# 괄호(내부 내용까지) 제거, 한자 제거

def remove_parentheses_and_hanja(text):
    if not isinstance(text, str):
        return ""
    # 괄호와 내부 내용 제거
    text = re.sub(r"\([^)]*\)", "", text)
    # 한자 제거
    text = re.sub(r"[\u4E00-\u9FFF\u3400-\u4DBF\uF900-\uFAFF]", "", text)
    # 양쪽 공백 정리
    return text.strip()

for c in ["title", "summary", "contents"]:
    df[c] = df[c].apply(remove_parentheses_and_hanja)

df.head(2)

,category,title,summary,contents
0,물품,가,죄수의 목에 채우는 형구.,보통 '칼'이라고 하였다. 칼은 마른 나무널판으로 만든 형틀로 죄수의 목에 씌워 보...
1,문헌,20공신회맹축 - 보사공신녹훈후,1694년 갑술환국으로 재집권한 서인이 보사공신 회맹 때의 회맹문과 복훈 때의 축문...,숙종대에 갑술환국으로 서인이 재집권하면서 보사공신 중 1689년 기사환국으로 파훈되...

In [3]:
# OpenAI API를 사용하여 contents 컬럼에서 단어 추출 후 title에 추가
import json
from openai import OpenAI

client = OpenAI()

def extract_keywords_from_contents(title, summary, contents):
    if not isinstance(contents, str) or not contents.strip():
        return []
    
    # OpenAI API 호출을 위한 프롬프트 설정
    prompt_template = """
            You are helping to build a Korean history glossary for elementary school students.

            Goal:
                From the given Korean-history text, extract difficult terms for an average Korean elementary school student (age 10–12), and write simple definitions for each term.

            Rules:
                1. Do NOT include the main term given in "TITLE" as an extracted term.
                2. Extract only important historical or conceptual terms from the CONTENTS text
                   that are likely to be difficult for elementary students
                   (for example: 한자어, 역사 용어, 행정 단위, 제도 이름 등).
                3. Do NOT include very common words (예: 사람, 나라, 전쟁, 생활, 도움 등).
                4. For each extracted term, write a short definition in EASY KOREAN
                   that an elementary school student can understand.
                5. The definition should be 1–2 sentences, no more than 40 Korean characters if possible.
                6. If there are no suitable difficult terms, return an empty list.
                7. Output MUST be valid JSON in the following format:

            {{
                "extra_terms": [
                    {{
                    "term": "...",
                    "definition": "..."
                    }}
                ]
            }}

            Input:
            TITLE: "{title}"
            SUMMARY: "{summary}"
            CONTENTS: "{contents}"
            """
    prompt = prompt_template.format(
        title=title.replace('"', '\\"'),
        summary=summary.replace('"', '\\"') if isinstance(summary, str) else "",
        contents=contents.replace('"', '\\"'),
    )
    
    # OpenAI Chat Completions API 호출
    response = client.chat.completions.create(
        model="gpt-5-nano",
        # 가능하면 JSON 강제 (선택)
        # response_format={"type": "json_object"},
        messages=[
            {
                "role": "user",
                "content": prompt,
            }
        ],
    )

    # 모델이 생성한 텍스트(JSON 문자열)를 추출
    if (
        not response.choices 
        or not response.choices[0].message 
        or not response.choices[0].message.content
    ):
        print("Empty response:", response)
        return []
    raw_output = response.choices[0].message.content.strip()

    # JSON 파싱
    try:
        data = json.loads(raw_output)
        extra_terms = data.get("extra_terms", [])
        # 리스트가 아닐 경우 방어 코드
        if not isinstance(extra_terms, list):
            return []
        return extra_terms
    except json.JSONDecodeError:
        # JSON 형식이 조금 틀어졌을 때를 대비한 예외 처리
        print("JSONDecodeError, raw_output:", raw_output)
        return []

In [4]:
import re

def clean_definition(text: str) -> str:
    """정의 끝의 '~에요', '~이에요', '~입니다', '~예요' 등을 잘라내기."""
    if not isinstance(text, str):
        return ""
    text = text.strip()
    # 끝부분 어미 제거
    text = re.sub(r"(이에요|에요|입니다|예요)\s*[\.\!]*$", "", text)
    return text

def update_row_with_terms(row):
    """
    한 행에서:
      - 추출된 용어 리스트를 반환.
      - 원래 title/summary는 수정하지 않음.
    반환 형식: [(term, definition), ...]
    """
    extra_terms = extract_keywords_from_contents(
        title=row["title"],
        summary=row.get("summary", "") or "",
        contents=row["contents"],
    )

    existing_title = str(row["title"])
    term_defs = []

    for t in extra_terms:
        term = (t.get("term") or "").strip()
        definition = clean_definition(t.get("definition", ""))

        # term이 없거나, 원래 title에 이미 포함된 용어는 제외
        if not term or term in existing_title:
            continue

        if not definition:
            continue

        term_defs.append((term, definition))

    return term_defs

In [5]:
from tqdm import tqdm
import csv
import os
from time import sleep

output_path = "output/result.csv"
start_idx = 5304  # 0-based 인덱스 기준 5304행부터 처리

# 파일 존재 여부 확인
file_exists = os.path.exists(output_path)

# output 폴더 생성 (없을 경우)
os.makedirs(os.path.dirname(output_path), exist_ok=True)

# 파일이 없을 때만 헤더 기록
if not file_exists:
    with open(output_path, "w", newline="", encoding="utf-8-sig") as f:
        writer = csv.writer(f)
        writer.writerow(["id", "title", "summary"])

batch = []
batch_size = 20

# 처리 구간만 슬라이스
df_to_process = df.iloc[start_idx:]

# tqdm 추가 (슬라이스 길이)
for idx, row in tqdm(df_to_process.iterrows(), total=len(df_to_process), desc="Processing rows"):
    # 원본 df의 인덱스 사용(슬라이스여도 원래 인덱스 유지)
    row_id = idx

    # 1) 먼저 원래 항목을 그대로 한 줄 기록
    original_title = row["title"]
    original_summary = row.get("summary", "") or ""
    batch.append([row_id, original_title, original_summary])

    try:
        # 2) 추출된 용어들을 각각 별도의 행으로 추가
        term_defs = update_row_with_terms(row)  # [(term, definition), ...]

        for term, definition in term_defs:
            batch.append([row_id, term, definition])

    except Exception as e:
        print(f"Error at row {idx}: {e}")
        # 원본 행은 이미 batch에 들어갔으므로 그대로 진행
        pass

    # batch 기준으로 주기적으로 CSV에 append
    if len(batch) >= batch_size:
        with open(output_path, "a", newline="", encoding="utf-8-sig") as f:
            writer = csv.writer(f)
            writer.writerows(batch)
        batch = []
        sleep(0.2)  # rate limit 완화용

# 마지막 batch 저장
if batch:
    with open(output_path, "a", newline="", encoding="utf-8-sig") as f:
        writer = csv.writer(f)
        writer.writerows(batch)

Processing rows:  36%|███▌      | 1793/5040 [19:25:37<231:23:39, 256.55s/it]

Error at row 7096: Connection error.

Processing rows:  36%|███▌      | 1794/5040 [19:25:38<162:18:07, 180.00s/it]

Error at row 7097: Connection error.

Processing rows:  36%|███▌      | 1795/5040 [19:25:40<113:56:55, 126.41s/it]

Error at row 7098: Connection error.

Processing rows:  36%|███▌      | 1796/5040 [20:24:52<1040:13:06, 1154.37s/it]

Error at row 7099: Connection error.

Processing rows:  36%|███▌      | 1797/5040 [20:24:54<728:16:13, 808.44s/it]

Error at row 7100: Connection error.

Processing rows:  36%|███▌      | 1798/5040 [20:24:55<510:00:01, 566.32s/it]

Error at row 7101: Connection error.

Processing rows:  36%|███▌      | 1799/5040 [20:24:56<357:15:31, 396.83s/it]

Error at row 7102: Connection error.

Processing rows:  36%|███▌      | 1800/5040 [20:24:58<250:24:05, 278.22s/it]

Error at row 7103: Connection error.

Processing rows:  36%|███▌      | 1801/5040 [20:24:59<175:34:00, 195.13s/it]

Error at row 7104: Connection error.

Processing rows:  36%|███▌      | 1802/5040 [20:34:11<271:49:43, 302.22s/it]

Error at row 7105: Connection error.

Processing rows:  36%|███▌      | 1803/5040 [20:34:13<190:33:26, 211.93s/it]

Error at row 7106: Connection error.

Processing rows:  36%|███▌      | 1804/5040 [20:34:14<133:43:35, 148.77s/it]

Error at row 7107: Connection error.

Processing rows:  36%|███▌      | 1805/5040 [20:34:15<93:56:24, 104.54s/it]

Error at row 7108: Connection error.

Processing rows:  36%|███▌      | 1806/5040 [20:34:17<66:07:13, 73.60s/it]

Error at row 7109: Connection error.

Processing rows:  36%|███▌      | 1807/5040 [20:34:18<46:36:08, 51.89s/it]

Error at row 7110: Connection error.

Processing rows:  36%|███▌      | 1808/5040 [20:34:19<32:55:22, 36.67s/it]

Error at row 7111: Connection error.

Processing rows:  36%|███▌      | 1809/5040 [20:34:20<23:24:19, 26.08s/it]

Error at row 7112: Connection error.

Processing rows:  36%|███▌      | 1810/5040 [20:34:22<16:44:59, 18.67s/it]

Error at row 7113: Connection error.

Processing rows:  36%|███▌      | 1811/5040 [20:34:23<12:05:47, 13.49s/it]

Error at row 7114: Connection error.
Error at row 7115: Connection error.

Processing rows:  36%|███▌      | 1813/5040 [20:34:26<6:35:09,  7.35s/it]

Error at row 7116: Connection error.

Processing rows:  36%|███▌      | 1814/5040 [20:34:28<4:58:57,  5.56s/it]

Error at row 7117: Connection error.

Processing rows:  36%|███▌      | 1815/5040 [20:34:29<3:49:14,  4.26s/it]

Error at row 7118: Connection error.

Processing rows:  36%|███▌      | 1816/5040 [20:34:30<3:01:01,  3.37s/it]

Error at row 7119: Connection error.

Processing rows:  36%|███▌      | 1817/5040 [20:34:31<2:25:29,  2.71s/it]

Error at row 7120: Connection error.

Processing rows:  36%|███▌      | 1818/5040 [20:34:32<2:02:03,  2.27s/it]

Error at row 7121: Connection error.

Processing rows:  36%|███▌      | 1819/5040 [20:34:34<1:46:36,  1.99s/it]

Error at row 7122: Connection error.

Processing rows:  36%|███▌      | 1820/5040 [20:34:35<1:37:57,  1.83s/it]

Error at row 7123: Connection error.

Processing rows:  36%|███▌      | 1821/5040 [20:34:37<1:31:55,  1.71s/it]

Error at row 7124: Connection error.

Processing rows:  36%|███▌      | 1822/5040 [20:34:38<1:26:01,  1.60s/it]

Error at row 7125: Connection error.

Processing rows:  36%|███▌      | 1823/5040 [20:34:39<1:19:56,  1.49s/it]

Error at row 7126: Connection error.

Processing rows:  36%|███▌      | 1824/5040 [20:34:41<1:18:39,  1.47s/it]

Error at row 7127: Connection error.

Processing rows:  36%|███▌      | 1825/5040 [20:34:42<1:17:52,  1.45s/it]

Error at row 7128: Connection error.

Processing rows:  36%|███▌      | 1826/5040 [20:34:43<1:14:59,  1.40s/it]

Error at row 7129: Connection error.

Processing rows:  36%|███▋      | 1827/5040 [20:34:45<1:13:40,  1.38s/it]

Error at row 7130: Connection error.

Processing rows:  36%|███▋      | 1828/5040 [20:34:46<1:10:39,  1.32s/it]

Error at row 7131: Connection error.

Processing rows:  36%|███▋      | 1829/5040 [20:34:47<1:10:33,  1.32s/it]

Error at row 7132: Connection error.

Processing rows:  36%|███▋      | 1830/5040 [20:34:48<1:08:00,  1.27s/it]

Error at row 7133: Connection error.

Processing rows:  36%|███▋      | 1831/5040 [20:34:50<1:07:31,  1.26s/it]

Error at row 7134: Connection error.

Processing rows:  36%|███▋      | 1832/5040 [20:34:51<1:10:58,  1.33s/it]

Error at row 7135: Connection error.

Processing rows:  36%|███▋      | 1833/5040 [20:34:53<1:13:35,  1.38s/it]

Error at row 7136: Connection error.

Processing rows:  36%|███▋      | 1834/5040 [20:34:54<1:12:04,  1.35s/it]

Error at row 7137: Connection error.

Processing rows:  36%|███▋      | 1835/5040 [20:34:55<1:10:11,  1.31s/it]

Error at row 7138: Connection error.

Processing rows:  36%|███▋      | 1836/5040 [20:34:56<1:11:19,  1.34s/it]

Error at row 7139: Connection error.

Processing rows:  36%|███▋      | 1837/5040 [20:34:58<1:13:51,  1.38s/it]

Error at row 7140: Connection error.

Processing rows:  36%|███▋      | 1838/5040 [20:34:59<1:11:37,  1.34s/it]

Error at row 7141: Connection error.

Processing rows:  36%|███▋      | 1839/5040 [20:35:01<1:12:20,  1.36s/it]

Error at row 7142: Connection error.

Processing rows:  37%|███▋      | 1840/5040 [20:35:02<1:13:08,  1.37s/it]

Error at row 7143: Connection error.

Processing rows:  37%|███▋      | 1841/5040 [20:35:03<1:14:35,  1.40s/it]

Error at row 7144: Connection error.

Processing rows:  37%|███▋      | 1842/5040 [20:35:05<1:15:08,  1.41s/it]

Error at row 7145: Connection error.

Processing rows:  37%|███▋      | 1843/5040 [20:35:06<1:15:27,  1.42s/it]

Error at row 7146: Connection error.

Processing rows:  37%|███▋      | 1844/5040 [20:35:08<1:13:19,  1.38s/it]

Error at row 7147: Connection error.

Processing rows:  65%|██████▌   | 3283/5040 [39:38:29<27:11:27, 55.71s/it]

JSONDecodeError, raw_output: {
  "extra_terms": [
    {
      "term": "서사관",
      "definition": "조선 시대에 글과 문서를 맡아 기록을 관리하는 벼슬이다."
    },
    {
      "term": "호조참의",
      "definition": "조선의 재정과 물가를 다루는 호조의 높은 벼슬이다."
    },
    {
      "term": "지돈녕부사",
      "definition": "임금의 비서를 돕고 나라 일을 주관하던 벼슬이다."
    },
    {
      "term": "판결사",
      "definition": "법과 판결을 맡아 다스리던 관리 직책이다."
    },
    {
      "term": "개성부유수",
      "definition": "개성부의 지방 관리를 가리키는 직함이다."
    },
    {
      "term": "광주목사",
      "definition": "광주 지역을 다스리던 지방 관리다."
    },
    {
      "term": "천거",
      "definition": "많은 사람의 추천으로 벼슬에 임명되는 제도다."
    },
    {
      "term": "초서",
      "definition": "빨리 쓰는 서체로, 한자의 초서다."
    },
    {
      "term": "예서",
      "다음",
      "definition": "정갈하고 느리게 쓰는 서체로 예서다."
    },
    {
      "term": "묵화",
      "definition": "먹으로 그리는 그림으로 색을 쓰지 않는다."
    },
    {
      "term": "책례도감",
      "definition": "의식과 예절을 관리하는 관청의 이름이다."
    }
  ]
}

Processing rows:  73%|███████▎  | 3661/5040 [44:27:37<19:06:30, 49.88s/it]

JSONDecodeError, raw_output: {
  "extra_terms": [
    {
      "term": "자",
      "definition": "자(字)는 어른이 되며 쓰는 또 다른 이름이다."
    },
    {
      "term": "호",
      "definition": "호(號)는 글이나 예술에서 쓰는 또 다른 이름이다."
    },
    {
      "term": "본관",
      "definition": "본관은 가문의 시작점이나 뿌리를 나타내는 이름이다."
    },
    {
      "term": "생원",
      "definition": "생원은 과거 시험의 처음 합격자이다."
    },
    {
      "term": "진사",
      "	definition": "진사는 과거 시험의 두 번째 합격자다."
    },
    {
      "term": "장원",
      "definition": "장원은 과거에서 1등으로 합격한 사람이다."
    },
    {
      "term": "급제",
      "definition": "급제는 시험에 합격해 벼슬을 얻은 상태다."
    },
    {
      "term": "문집",
      "definition": "문집은 작가의 글을 모아 만든 책이다."
    },
    {
      "term": "창주집",
      "definition": "창주집은 차운로가 남긴 글 모음이다."
    },
    {
      "term": "군수",
      "definition": "군수는 고을을 다스리는 관리다."
    },
    {
      "term": "현감",
      "definition": "현감은 현의 행정을 맡는 관리다."
    },
    {
      "term": "부사",
      "definition": "부사는 고을의 관리로 지역을 다스린다."
    },
    {
      "term": "첨정",
      "definition": "첨정은 조선 시대의 관리 직책 중 하나다."
    }
  ]
}

Processing rows:  90%|████████▉ | 4517/5040 [55:59:30<7:58:53, 54.94s/it]

JSONDecodeError, raw_output: {
  "extra_terms": [
    {
      "term": "무과",
      "definition": "조선 시대 군인을 뽑는 시험이다."
    },
    {
      "term": "과규",
      "definition": "시험의 규칙과 절차를 말한다."
    },
    {
      "term": "급제",
      "definition": "시험에 합격하여 관리가 되는 것을 말한다."
    },
    {
      "term": "충장장",
      "definition": "조선 시대의 군사 직책으로, 용맹한 장수를 맡는 자리다."
    },
    {
      "term": "우림장",
      "definition": "조선 시대의 관리 직책 이름으로, 보급을 맡는 자리다."
    },
    {
      "term": "전옥",
      "definition": "감옥에 갇히는 곳을 말한다."
    },
    {
      "term": "홍경래의 난",
      "definition": "1811년 무렵 함경도에서 벌어진 큰 반란이다."
    },
    {
      "term": "가의대부",
      "definition": "높은 관리의 직책 이름이다."
    },
    {
      "term": "통제사",
      "definition": "조선 시대 관리 직책으로 군사 업무를 맡는 자리다."
    },
    {
      "term": "정려",
      "st" : "definition": "공로가 큰 사람을 기리는 표지나 사당이다."
    },
    {
      "term": "배향",
      "definition": "위패를 어느 사당에 모시고 기억하는 일이다."
    },
    {
      "term": "추증",
      "definition": "사후에 벼슬을 올려 주는 것이라고 한다."
    }
  ]
}

Processing rows:  91%|█████████ | 4582/5040 [56:54:30<6:28:29, 50.89s/it]

Error at row 9885: Connection error.

Processing rows:  91%|█████████ | 4583/5040 [56:54:31<4:34:41, 36.06s/it]

Error at row 9886: Connection error.

Processing rows:  91%|█████████ | 4584/5040 [56:54:32<3:15:05, 25.67s/it]

Error at row 9887: Connection error.

Processing rows:  91%|█████████ | 4585/5040 [56:59:13<12:54:52, 102.18s/it]

Error at row 9888: Connection error.

Processing rows:  91%|█████████ | 4586/5040 [56:59:15<9:04:10, 71.92s/it]

Error at row 9889: Connection error.

Processing rows:  91%|█████████ | 4587/5040 [56:59:16<6:22:44, 50.69s/it]

Error at row 9890: Connection error.

Processing rows:  91%|█████████ | 4588/5040 [58:28:11<205:24:17, 1635.97s/it]

Error at row 9891: Connection error.

Processing rows:  91%|█████████ | 4589/5040 [58:28:12<143:31:21, 1145.64s/it]

Error at row 9892: Connection error.

Processing rows:  91%|█████████ | 4590/5040 [58:28:14<100:17:57, 802.40s/it]

Error at row 9893: Connection error.

Processing rows:  91%|█████████ | 4591/5040 [58:28:15<70:05:53, 562.03s/it]

Error at row 9894: Connection error.

Processing rows:  91%|█████████ | 4592/5040 [58:28:16<49:00:30, 393.82s/it]

Error at row 9895: Connection error.

Processing rows: 100%|██████████| 5040/5040 [64:45:39<00:00, 46.26s/it]

In [18]:
# 없는 행 확인
import pandas as pd

# 1) 컬럼명이 없는 CSV 읽기
df = pd.read_csv("output/result.csv", header=None, names=["id", "term", "description"])

# 2) expected 범위 정의
expected_ids = set(range(0, 10343))

actual_ids = set(df['id'].unique())
missing_ids = expected_ids - actual_ids

print("Missing IDs:", sorted(missing_ids))

Missing IDs: []

In [19]:
df.to_csv("output/result_edited1.csv", index=False)

In [20]:
df['term'].value_counts()

term
본관      1954
시호      1202
병과      1110
급제      1080
임진왜란     931
        ...
전발무사       1
상형추의       1
의율차례       1
비상전초       1
경사요의       1
Name: count, Length: 33947, dtype: int64

In [14]:
df[df['id']==7147]

         id term                      description
91948  7147  이천기  조선 후기에, 승지, 한림, 삼사이랑 등을 역임한 문신.

In [15]:
df['term'].nunique()

33947

In [16]:
df.shape[0]

131641

In [9]:
print("원본 길이 :",df.shape[0])
# [term, description] 중복 제거
df  = df.drop_duplicates(subset=["term", "description"]).reset_index(drop=True)
print("중복 제거 후 길이 :", df.shape[0])

원본 길이 : 131641
중복 제거 후 길이 : 125258

In [24]:
# 하나 이상인 것
term_counts = df['term'].value_counts()

# 두 번 이상 등장하는 term만
duplicated_terms = term_counts[term_counts > 1]

print(duplicated_terms)

term
본관      1954
시호      1202
병과      1110
급제      1080
임진왜란     931
        ...
충무         2
폐습         2
춘추관사       2
석비         2
홍위         2
Name: count, Length: 9157, dtype: int64

In [25]:
print("두 번 이상 등장하는 term 종류 수 :", (term_counts > 1).sum())

두 번 이상 등장하는 term 종류 수 : 9157

In [26]:
print("두 번 이상 등장하는 term이 차지하는 행 수 :", term_counts[term_counts > 1].sum())

두 번 이상 등장하는 term이 차지하는 행 수 : 106851

In [40]:

# term 에서 중복 제거
# description 길이 계산
df["desc_len"] = df["description"].str.len()

# term별로 desc_len이 가장 긴 행만 남기기
df_unique_term = (
    df.sort_values(["term", "desc_len"], ascending=[True, False])
      .drop_duplicates(subset=["term"], keep="first")
      .drop(columns=["desc_len"])
      .reset_index(drop=True)
)

print("term 기준 유니크 개수:", df_unique_term["term"].nunique())
df_unique_term.to_csv("output/result_term_dedup_longest.csv", index=False)

term 기준 유니크 개수: 33947

In [41]:
df_unique_term[df_unique_term["term"]=="가(枷)"]

     id  term         description
395   0  가(枷)  죄수의 목에 채우는 형구(刑具).

In [42]:
# 한자 제거 
import re
def remove_hanja(text):
    if not isinstance(text, str):
        return ""
    # 한자 제거
    text = re.sub(r"[\u4E00-\u9FFF\u3400-\u4DBF\uF900-\uFAFF]", "", text)
    # 양쪽 공백 정리
    return text.strip()

# 한자 제거 적용
df_unique_term["term"] = df_unique_term["term"].apply(remove_hanja)
df_unique_term["description"] = df_unique_term["description"].apply(remove_hanja)

In [43]:
# 한자 제거 후 () 내 빈칸이라면 제거
def remove_empty_parentheses(text):
    if not isinstance(text, str):
        return ""
    # 괄호 안이 완전히 공백이 된 경우 → 괄호 자체 제거
    text = re.sub(r"\(\s*\)", "", text)

    # 괄호 안에 기호만 있는 경우 → 괄호 자체 제거
    text = re.sub(r"\([\s\W]*\)", "", text)

    # 괄호 안에 한글이 있는데 괄호 앞 뒤로는 공백인 경우 → 괄호만 제거
    # (비삼망)은 -> 비삼망
    text = re.sub(r"\(([가-힣]+)\)", r"\1", text)
    
    # 양쪽 공백 정리
    return text.strip()
df_unique_term["term"] = df_unique_term["term"].apply(remove_empty_parentheses)
df_unique_term["description"] = df_unique_term["description"].apply(remove_empty_parentheses)

In [44]:
df_unique_term.to_csv("output/result_no_hanja.csv", index=False)

In [47]:
# term이 빈칸인 행 개수
(df_unique_term["term"].str.strip() == "").sum()

np.int64(57)

In [48]:
# term이 빈칸인 행 제거
df_unique_term = df_unique_term[df_unique_term["term"].str.strip() != ""].reset_index(drop=True)
df_unique_term.to_csv("output/result_no_hanja_ver2.csv", index=False)

In [57]:
# 서술형 뜻풀이 -> 명사형 정리

df_no_hanja = pd.read_csv("output/result_no_hanja_ver2.csv")

def clean_desc(text: str) -> str:
    if not isinstance(text, str):
        return text
    t = text.strip()

    # 1) 흔한 서술형/정의형 어미 제거 (길이가 긴 패턴부터)
    patterns = [
        r"(말하는\s*것입니다?\.)?$",
        r"(말하는\s*것입니다?)?$",
        r"(말하는\s*것\.)?$",
        r"(말하는\s*것)$",
        r"(말합니다?\.)?$",
        r"(말합니다?)?$",
        r"(말이다\.)?$",
        r"(말이다)$",
        r"(말이다)$",
        r"(뜻이다\.)?$",
        r"(뜻이다)$",
        r"(뜻)$",
        r"(뜻을 말한다\.)?$",
        r"(뜻을 말한다)$",
        r"(뜻한다\.)?$",
        r"(뜻한다)$",
        r"(구분이다\.)?$",
        r"(구분이다)$",
        r"(단계이다\.)?$",
        r"(단계이다)$",
        r"(단계이다)$",
        r"(단위이다\.)?$",
        r"(단위이다)$",
        r"(표기이다\.)?$",
        r"(표기이다)$",
        r"(것이다\.)?$",
        r"(것이다)$",
        r"(하였다\.)?$",
        r"(하였다)$",
        r"(했다\.)?$",
        r"(했다)$",
        r"(였다\.)?$",
        r"(였다)$",
        r"(이다\.)?$",
        r"(이다)$",
        r"(다\.)$",
    ]

    for p in patterns:
        t = re.sub(p, "", t).strip()

    # 2) 끝의 불필요한 마침표/쉼표 제거
    t = re.sub(r"[\.·,]+$", "", t).strip()

    return t

df_no_hanja["desc_norm"] = df_no_hanja["description"].astype(str).apply(normalize_desc)
df_no_hanja = df_no_hanja.drop(columns=["description"]).rename(columns={"desc_norm": "description"})

In [58]:
df_no_hanja.to_csv("output/result_no_hanja_ver3.csv", index=False)

In [ ]:
# 번역
# term은 로마자표기법으로 definition은 영어로 번역

In [ ]:
# term 컬럼을 prompt로 변경 : 임진왜란 -> 임진왜란의 뜻을 알려줘
# category가 "인물"인 행 제외
df_filtered = df[df['category'] != "인물"].copy()
df_filtered['prompt'] = df_filtered['term'].apply(lambda x: f"{x}의 뜻을 알려줘")

# category가 "인물"인 행
# 조사 : 선행체언에 따라 다름 - 선행체언이 자음으로 끝날 때 '이' 사용, 모음으로 끝날 때 '가' 사용
df_person = df[df['category'] == "인물"].copy()

def add_particle(name):
    if not name:
        return name
    last_char = name[-1]
    # 한글 자음과 모음의 유니코드 범위
    jongseong_start = 0x11A8
    jongseong_end = 0x11C2
    # 마지막 글자의 종성 추출
    char_code = ord(last_char) - 0xAC00
    jongseong_index = char_code % 28
    if jongseong_index == 0:
        return f"{name}가"
    else:
        return f"{name}이"
    
df_person['prompt'] = df_person['term'].apply(lambda x: f"{add_particle(x)} 누구야?")